name: echoo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  window_manager: ^0.3.9
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  screen_retriever: ^0.1.9
  encrypt: ^5.0.3
  url_launcher: ^6.2.5
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
